version: "3.8"

name: npo_automotive_dev

services:
  server:
    container_name: "npo_automotive_server_dev"
    restart: always
    build: server
    command: npm run start:prod
    user: 1000:1000
    env_file:
      - ./dev.env
    depends_on:
      - db
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/node_modules
  nginx:
    image: nginx
    restart: "no"
    container_name: "npo_automotive_nginx_dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/prod:/etc/nginx/conf.d
  db:
    container_name: npo_automotive_db_dev
    image: postgres:17
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/dev:/var/lib/postgresql/data/pgdata
