version: "3.8"

name: npo_automotive_local

services:
  client:
    container_name: "npo_automotive_client_local"
    build:
      context: ./client
      dockerfile: Dockerfile_local
    expose:
      - 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./client:/app
  server:
    container_name: "npo_automotive_server_local"
    restart: always
    build:
      context: server
      dockerfile: Dockerfile_local
    user: 1000:1000
    env_file:
      - ./local.env
    depends_on:
      - db
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server:/app
  nginx:
    image: nginx
    restart: "no"
    container_name: "npo_automotive_nginx_local"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${DOCKER_PORT:-4000}:80
    depends_on:
      - server
      - client
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/local:/etc/nginx/conf.d
  db:
    container_name: npo_automotive_db_local
    image: postgres:17
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/local:/var/lib/postgresql/data/pgdata
  dbgate:
    image: dbgate/dbgate
    container_name: npo_automotive_dbgate_local
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    expose:
      - 3000
    volumes:
      - ./dbgate/local:/root/.dbgate
    environment:
      WEB_ROOT: /dba
